blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/OpenListTeam/OpenList/discussions
    about: Discuss / 讨论、问题、想法等
  - name: Chat
    url: https://t.me/OpenListTeam
    about: Chat with us / 与我们聊天
