name: Sync to Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync GitHub to Gitee
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      - name: Create single commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Create a new branch
          git checkout --orphan new-main
          git add .
          git commit -m "Sync from GitHub: $(date)"

          # Add Gitee remote and force push
          git remote add gitee ${{ vars.GITEE_REPO_URL }}
          git push --force gitee new-main:main
